apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-two-tier-deployment
  labels:
    app: two-tier-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
      - name: python-container
        image: 975261999957.dkr.ecr.us-east-2.amazonaws.com/flask-two-tier:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_HOST
            value: "mysql"  # Mysql pod IP will be placed here
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "admin"
          - name: MYSQL_DB
            value: "mydb"
        ports:
        - containerPort: 5000 

---
apiVersion: v1
kind: Service
metadata:
  name: two-tier-service
spec:
  type: NodePort
  selector:
    app: two-tier-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007

