kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_DATABASE
            value: "mydb"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            value: "admin"
          - name: MYSQL_PASSWORD
            value: "admin"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql #It's inside the container
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-pvc

